fix: error when distrobox missing

diff --git a/.chezmoiscripts/run_onchange_after_update-distrobox.sh.tmpl b/.chezmoiscripts/run_onchange_after_update-distrobox.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_update-distrobox.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_update-distrobox.sh.tmpl
@@ -1,4 +1,8 @@
 #!/bin/bash
+if ! command -v distrobox >/dev/null 2>&1; then
+echo "distrobox: command not found. Skipping assemble." >&2
+exit 0
+fi
 
 # hash: {{ include "dot_config/distrobox/distrobox.ini" | sha256sum }}
 distrobox assemble create --replace --file ~/.config/distrobox/distrobox.ini
